import React, { useState } from 'react';
import { useApp } from '../contexts/AppContext';
import { Plus, Clock, CheckCircle, AlertCircle, Share2, Mail, ExternalLink, Copy, Check } from 'lucide-react';
import { Project, ProjectStatus } from '../types';
import NewProjectModal from './NewProjectModal';
import { generateClientEmail } from '../services/gemini';

const StatusBadge: React.FC<{ status: ProjectStatus }> = ({ status }) => {
  switch (status) {
    case ProjectStatus.APPROVED:
      return (
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-700 border border-emerald-200">
          <CheckCircle size={14} /> Approved
        </span>
      );
    case ProjectStatus.CHANGES_REQUESTED:
      return (
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-700 border border-amber-200">
          <AlertCircle size={14} /> Changes
        </span>
      );
    default:
      return (
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-600 border border-blue-100">
          <Clock size={14} /> Pending
        </span>
      );
  }
};

const EmailGeneratorModal: React.FC<{ project: Project; onClose: () => void }> = ({ project, onClose }) => {
  const [emailBody, setEmailBody] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const generate = async (type: 'initial' | 'followup' | 'approved_thanks') => {
    setLoading(true);
    const text = await generateClientEmail(project.clientName, project.title, type);
    // Append the link
    const link = `${window.location.origin}/#/client/${project.id}`;
    setEmailBody(`${text}\n\nReview here: ${link}`);
    setLoading(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(emailBody);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden animate-fade-in">
        <div className="p-5 border-b flex justify-between items-center bg-gray-50">
          <h3 className="font-bold text-gray-700 flex items-center gap-2">
            <Mail size={18} className="text-purple-500" /> AI Email Assistant
          </h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><Plus size={24} className="rotate-45" /></button>
        </div>
        <div className="p-6 space-y-4">
          <div className="flex gap-2">
            <button 
              onClick={() => generate('initial')}
              disabled={loading}
              className="flex-1 py-2 text-sm font-medium bg-white border border-gray-200 hover:bg-gray-50 rounded-lg transition-colors"
            >
              New Link
            </button>
            <button 
              onClick={() => generate('followup')}
              disabled={loading}
              className="flex-1 py-2 text-sm font-medium bg-white border border-gray-200 hover:bg-gray-50 rounded-lg transition-colors"
            >
              Follow Up
            </button>
            <button 
              onClick={() => generate('approved_thanks')}
              disabled={loading}
              className="flex-1 py-2 text-sm font-medium bg-white border border-gray-200 hover:bg-gray-50 rounded-lg transition-colors"
            >
              Thank You
            </button>
          </div>

          <div className="relative">
            <textarea
              className="w-full h-40 p-4 bg-gray-50 rounded-xl border border-gray-200 focus:ring-2 focus:ring-purple-400 focus:outline-none text-sm leading-relaxed resize-none"
              value={loading ? "Generating..." : emailBody}
              placeholder="Select an option above to generate a draft..."
              readOnly
            />
            {emailBody && !loading && (
              <button 
                onClick={copyToClipboard}
                className="absolute bottom-3 right-3 p-2 bg-white rounded-lg shadow-sm border border-gray-200 hover:text-blue-600 transition-colors"
                title="Copy to clipboard"
              >
                {copied ? <Check size={16} className="text-green-500"/> : <Copy size={16} />}
              </button>
            )}
          </div>
          
          <p className="text-xs text-center text-gray-400">Content generated by Gemini 3 Flash</p>
        </div>
      </div>
    </div>
  );
};

const Dashboard: React.FC = () => {
  const { projects, addProject } = useApp();
  const [showNewProject, setShowNewProject] = useState(false);
  const [selectedProjectForEmail, setSelectedProjectForEmail] = useState<Project | null>(null);

  const stats = {
    pending: projects.filter(p => p.status === ProjectStatus.PENDING).length,
    approved: projects.filter(p => p.status === ProjectStatus.APPROVED).length,
    changes: projects.filter(p => p.status === ProjectStatus.CHANGES_REQUESTED).length,
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold shadow-lg shadow-blue-500/30">
              AF
            </div>
            <span className="font-bold text-gray-800 text-lg tracking-tight">ApproveFlow</span>
          </div>
          <button
            onClick={() => setShowNewProject(true)}
            className="bg-gray-900 hover:bg-black text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 shadow-lg"
          >
            <Plus size={16} /> New Project
          </button>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
        {/* Stats Row */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Pending</p>
              <p className="text-2xl font-bold text-gray-800">{stats.pending}</p>
            </div>
            <div className="w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center text-blue-500">
              <Clock size={20} />
            </div>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Needs Changes</p>
              <p className="text-2xl font-bold text-gray-800">{stats.changes}</p>
            </div>
            <div className="w-10 h-10 rounded-full bg-amber-50 flex items-center justify-center text-amber-500">
              <AlertCircle size={20} />
            </div>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Approved</p>
              <p className="text-2xl font-bold text-gray-800">{stats.approved}</p>
            </div>
            <div className="w-10 h-10 rounded-full bg-emerald-50 flex items-center justify-center text-emerald-500">
              <CheckCircle size={20} />
            </div>
          </div>
        </div>

        {/* Project Grid */}
        <h2 className="text-lg font-bold text-gray-800 mb-4">Active Projects</h2>
        
        {projects.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-gray-300">
            <p className="text-gray-400 mb-4">No projects yet.</p>
            <button onClick={() => setShowNewProject(true)} className="text-blue-600 font-medium hover:underline">Create your first one</button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {projects.map((project) => (
              <div key={project.id} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow group">
                <div className="relative h-48 bg-gray-100 overflow-hidden">
                  <img src={project.imageUrl} alt={project.title} className="w-full h-full object-cover transition-transform group-hover:scale-105 duration-500" />
                  <div className="absolute top-3 right-3">
                    <StatusBadge status={project.status} />
                  </div>
                </div>
                <div className="p-5">
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <h3 className="font-bold text-gray-800 truncate pr-4">{project.title}</h3>
                      <p className="text-sm text-gray-500">{project.clientName}</p>
                    </div>
                  </div>
                  <div className="mt-4 pt-4 border-t border-gray-50 flex items-center gap-2">
                    <a 
                      href={`#/client/${project.id}`} 
                      target="_blank" 
                      rel="noreferrer" 
                      className="flex-1 py-2 text-center text-sm font-medium text-gray-600 bg-gray-50 hover:bg-gray-100 rounded-lg transition-colors flex items-center justify-center gap-2"
                    >
                      <ExternalLink size={14} /> View
                    </a>
                    <button 
                      onClick={() => setSelectedProjectForEmail(project)}
                      className="p-2 text-gray-400 hover:text-purple-600 bg-gray-50 hover:bg-purple-50 rounded-lg transition-colors"
                      title="Generate Email"
                    >
                      <Mail size={18} />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {showNewProject && (
        <NewProjectModal 
          onClose={() => setShowNewProject(false)} 
          onSave={addProject}
        />
      )}

      {selectedProjectForEmail && (
        <EmailGeneratorModal 
          project={selectedProjectForEmail}
          onClose={() => setSelectedProjectForEmail(null)}
        />
      )}
    </div>
  );
};

export default Dashboard;